.eslintrc
src/components/amenities/index.jsx
src/components/availability/index.jsx
src/components/breadcrumbs/index.jsx
src/components/button/index.jsx
src/components/callout/index.jsx
src/components/contentHeader/index.jsx
src/components/contentSectionList/index.jsx
src/components/dropdown/index.jsx
src/components/flyout/index.jsx
src/components/form/checkbox.jsx
src/components/form/range.jsx
src/components/form/select.jsx
src/components/heading/index.jsx
src/components/icon/index.jsx
src/components/imageHero/index.jsx
src/components/listItem/index.jsx
src/components/listItemBookable/index.jsx
src/components/location/index.jsx
src/components/moreLink/index.jsx
src/components/narrative/index.jsx
src/components/numberList/index.jsx
src/components/placeholder/index.jsx
src/components/relatedTour/index.jsx
src/components/tagList/index.jsx
src/components/toolbar/index.js
src/components/tooltip/index.jsx

This PR replaces vague prop types `React.PropTypes.array` and `React.PropTypes.object` with `React.PropTypes.arrayOf`, `React.PropTypes.objectOf` and `React.PropTypes.shape`.
It also updates the eslint config to throw errors if any of the vague prop types are used.

Make prop types more specific

---

.storybook/common.css
.storybook/config.js
README.md
package.json
stories/Colors.jsx
stories/data.json
stories/icons.jsx
stories/index.jsx
stories/styles.json

This is still a work-in-progress, but I thought it would be good to get it merged so others can use it.
There are still a few outstanding issues and things to work through:
- Some components don't render because they use media queries or keyframes applied via Radium. Radium requires a `StyleRoot` component to wrap components that use these features. In our current situation, the `StyleRoot` component is applied at the app level and not on a per-component basis.
- Some components have not yet been added to the Storybook; you will see these component names commented out in stories/index.jsx
- Lack of a global stylesheet; this may actually be a feature because it allows us to see the shortcomings of each component and add the appropriate styles to make the component fully reusable across …

Install, configure Storybook for component development

---

src/components/amenities/index.jsx
src/components/breadcrumbs/index.jsx
src/components/contentHeader/index.jsx
src/components/expandButton/index.jsx
src/components/form/checkbox.jsx
src/components/heading/index.jsx
src/components/icon/index.jsx
src/components/iconButton/index.jsx
src/components/mapMarker/index.jsx
src/components/moreLink/index.jsx
src/components/rating/index.jsx
src/components/shareMenu/index.jsx
src/components/shareMenu/item.jsx
src/components/shareMenu/styles.js
src/components/tag/index.jsx
src/components/tagList/index.jsx

Without a global stylesheet, some components fail to render properly.
Some of the updates include:
- Replacing rem with px because each app may define its own global font
size, which will render the components inconsistently
- Adding reset styles to certain elements, such as removing link
underlines and removing padding, margin on unordered lists
- Setting a font-family on components because there is no global
stylesheet to inherit from
- Update prop types validation

Update component styles

---

settings.json
src/components/sightsListItem/index.jsx
stories/index.jsx

Adds the sights list item element.
Existing component in Destinations - https://www.lonelyplanet.com/usa/alaska#experiences

add sights list item component

---

src/components/form/input.jsx

Previously there was no way to pass custom styles to the input or to pass on an onChange handler. This allows for both of those customizations.

adds ability to customize input field

---

package.json

Seemed to be breaking the publish to the NPM directory and I don't think we need to alias `npm run gh-pages`.

Remove custom publish script

---

src/components/recommendedArticles/index.jsx
stories/index.jsx

- Add props: `heading`, `calloutLabel`, `calloutHref `, `style`
- Replace `children` prop with `articles` prop; now an array of objects can be passed in to define ArticlePreview, rather than having to know that ArticlePreview itself should be passed as children

Update RelatedArticles component

---

package.json

I'll be adding the pre-commit in another pull request. It's just that there are a few lint errors that need fixed up before the pre-commit hook can be pushed to master. I wanted to get the lint script in there so at least it can be done manually for now.

Add lint script

---

src/components/tallCarousel/index.jsx

adds an extra pass through setting object to only overwrite the items you need to overwrite

tall carousel custom settings

---

src/components/mastheadSlider/index.jsx

min height was placing content off the visible slide

remove min height restrictions from masthead slider

---

src/components/spotlightZone/index.jsx

fixes https://github.com/lonelyplanet/dotcom-video/issues/97
changes zone text to be absolutely positioned from the top opposed to a large negative top margin which was pushing the text out of view at times.

update spotlight zone positioning

---

src/components/card/card.jsx
src/components/card/cardHeading.jsx
src/components/card/cardImage.jsx
src/components/thumbnailListItem/index.jsx
src/components/tileVideoPoster/index.jsx

In card, tile and list item components, the CoverPhoto scales slightly when hovered

Add hover scale effect to CoverPhoto

---

package.json
src/components/card/cardAnchor.jsx
src/components/cardShelfVideoSwiper/index.jsx
src/components/cardVideo/index.jsx
src/components/gradientOverlay/index.jsx
src/components/heading/index.jsx
src/components/heroImageContainer/index.jsx
src/components/link/index.jsx
src/components/mastheadSlider/index.jsx
src/components/newsArticleAuthor/index.jsx
src/components/sectionHeader/index.jsx
src/components/tallCarousel/index.jsx
src/components/tileVideo/index.jsx
src/components/typeSelector/index.jsx

fixes propType warnings
*had to remove the specific components allowed to be children of the `CarShelfVideoSwiper` component due to the fact that these components are wrapped in a Radium connector and were not registering as the underlying component

fix prop type warnings

---

src/components/tabbedNav/index.jsx

Radium throws a warning when -webkit-overflow-scrolling is used.

Use WebkitOverflowScrolling to fix radium warning

---

src/components/text/index.jsx
src/components/text/textAccent.jsx
src/components/text/textBodyArticle.jsx
src/components/text/textBodySmall.jsx
src/components/text/textHeading.jsx
src/components/text/textUppercase.jsx
src/utils/propTypes.js
stories/index.jsx

These components map to styles/typography and use utils/typography to apply the styles.
TextHeading is a stripped down version of Heading and the idea is to deprecate Heading in a future release. TextHeading was created 1) somewhat as an experiment to simplify Heading and 2) as to not break every implementation of Heading currently in use.

Create text components to match typography styles

---

src/components/mastheadSlider/index.jsx
src/components/slide/index.jsx

content was overflowing the main nav when content was too long or window was too short
this adds min height and lets the content expand responsively
reference https://github.com/lonelyplanet/dotcom-video/issues/177

update: responsive masthead and slide styles

---

src/components/slide/index.jsx

GTM will update the style attribute of the div with the targeted ad id. We can hide this div by default and let GTM take care of the rest. 
Also this passes in the entire id since this slide component may not only be used for video slides.

update: pass full ad id through as prop and hide by default

---

src/components/mastheadSlider/index.jsx

Fixes a bug where the first cloned slide, which is actually the last
slide, can sometimes appear while the slider is still loading.

Hide first cloned slide

---

src/components/articlePaginationItem/index.jsx

Use object-fit CSS property on the img element

Prevent ArticlePaginationItem image from stretching

---

src/components/calloutLink/index.jsx
src/components/listContainer/index.jsx

update border colors on components used in travel news, these will use new backpack colors instead of rizzo-next colors

update border colors on components used in travel news

---

src/components/navigation/index.jsx
src/components/navigation/navigation.jsx
src/components/navigation/navigationTab.jsx
stories/index.jsx

The goal of this PR is to simplify and standardize navigation components. Eventually these components will be used to deprecate TabbedNav and SectionalNav components as this was essentially a rewrite of those components in order to make the navigation more reusable.

Create navigation components

---

src/components/form/input.jsx
src/components/form/textarea.jsx

instead of passing specific props through to the input component, I spread all props onto the input. 
This is so we can just add any field that may be on an input without having to define it. 
I pulled off any styles from props to maintain the current way that these components are styled

update: pass through all props to input/textarea

---

src/components/avatarUpload/index.jsx

adds a function to the avatarUpload to pass out the newly uploaded image data. 
This way we will be able to pass the new image data out to Open Planet to save in profile

update: expose uploaded avatr image

---

src/components/socialShareContainer/index.jsx

An issue was discovered when Twitter's widgets JS is loaded onto a page where the SocialShare component is used.
From https://dev.twitter.com/web/intents
> Twitter’s widgets JavaScript will automatically handle creating child windows at the appropriate dimensions and firing appropriate JavaScript events when included on a webpage. We recommend rendering each web intent at 550px by 420px if you create your own web intent handlers.
This caused two pop-up windows to appear when the Twitter share button was clicked; one from the `window.open` function in SocialShareContainer and the second from Twitter's widget.
The solution I came up with was to check to see if the `window.__twttr` object was loaded on the page. When the widgets JS is loaded, it will create this object. I'm not sure if this …

Prevent double Twitter pop-up window

---

src/components/tabs/tabs.jsx

If `child` is null or undefined then `child.props` gives an error

Check for child in Tabs

---

src/components/socialLoginButton/index.jsx

style prop was getting passed directly on component so it cause the socialButton styles to be wiped away

fix: reorder social login props to not override styles

---

package.json

standard-version is used to help with automatic CHANGELOG
generation and publishing to npm. It replaces the scripts
that were used to help manually generate the CHANGELOG.
The available commands are as follows:
- `version`: Considered the "default" command to create a
new release, this command will automatically decide which
version number to bump (patch, minor, major) and will
require a manual push and publish
- `version:patch`: This command bypasses the automated
version bump and allows you to force a patch release
- `version:minor`: This command bypasses the automated
version bump and allows you to force a minor release
- `version:major`: This command bypasses the automated
version bump and allows you to force a major release
- `push`: This command is an alias to push and publish if …

Install standard-version module

---

settings.json
src/styles/zIndex.js

There needs to be more variation and intention with the z-index values.
Currently, many components use “modal” and then add or subtract values
to place the component on the desired layer. The addition of the global
log in modal has revealed that this method for setting z-index is not
very sustainable. Essentially, “modal” doesn’t mean much at this point
because too many components that aren’t a modal use it.
The goal here is to introduce some hierarchy within the z-index values.
Every component that sits on top of the page should not use “modal” or
“modal + 1”, because when an actual modal is rendered now, it may or
may not be placed on top of every other component. The stacking order
of components should be clearly defined and this should help.

Add new values for z-index

---

src/components/button/index.jsx

Prevents error in console about invalid value on `color` prop.

Add "gray" to Button color prop validation

---

src/components/button/index.jsx

This prevents the props from being applied to the element.
In the case of `href`, it would apply `href(unknown)` to the
element.

Set default href and role in Button to null

---

src/components/toast/index.jsx

As an accessibility concern, if the use has requested to
reduce motion via macOS or iOS, then the `prefers-reduced-motion`
media query will disable sliding in movement.
More on this topic: https://webkit.org/blog/7551/responsive-design-for-motion/

Add media query to disable motion in Toast

---

src/components/auth/README.md
src/components/auth/authContainer.jsx
src/components/auth/authDisclaimer.jsx
src/components/auth/authEmailLink.jsx
src/components/auth/authMessage.jsx
src/components/auth/authSocialButtons.jsx
src/components/auth/index.js

Auth components can be combined to create the UI for logging into
lonelyplanet.com. Some components are just wrappers of other components
with some extra styling (i.e., `AuthDisclaimer`, `AuthEmailLink`). These
components serve a very specific purpose and therefore shouldn't be used
on their own.
Deprecates ModalContentSocialAuth component

Create Auth components

---

src/styles/zIndex.js

This is to help with creating design tokens and is a temporary change.
One single object will be exported when the deprecated values are
removed.

Separate deprecated z-index values into their own object

---

CHANGELOG.md
src/components/multiStep/multiStepLogin.jsx

pulled multi step auth component into its own separate component so that `dotcom-connect` can use it without the modal.

Nf multi step auth content

---

stories/center.jsx

The Center component uses flexbox to center a component
horizontally and vertically within Storybook’s display area.
You can pass in an optional background color as well as
flexbox properties to control how the child component grows
and shrinks.
It can be used simply by wrapping a component in
stories/index.jsx like so:
```
<Center>
<Avatar />
</Center>
```

Add component to center components in storybook

---

.storybook/addons.js

This is so that the "knobs" tab shows first in the UI since
it is the most commonly used.

Reorder storybook addon imports

---

src/components/spotlightZone/index.jsx

Updated spotlightZone to allow HTML within its paragraph property value

---

package.json
src/components/typeahead/index.jsx
stories/data.json
stories/index.jsx
yarn.lock

Currently the typeahead component is in a [separate repo](https://github.com/thomasthesecond/react-typeahead/tree/refactor). This is a fork
and refactor of another popular (but poorly maintained) typeahead
component. I think my goal is to clean it up some more and publish it
properly, but for now I wanted to get it working and into Backpack.
Does anyone see any issues with this approach?
Closes #298

Create Typeahead component

---

src/components/toast/index.jsx

min-width is now a calculated value using dimensions.minWidth and the
padding value; width uses calc to allow left and right margin when
scaling between min- and max-width.

Adjust min-width and set width for Toast

---

src/components/checkbox/checkboxComponent.jsx

In legacy versions of IE, the checkbox input type cannot be
styled and the appearance property is not supported. Because
of this, there was a bug in IE where the fake input’s border
and the actual input’s border both appeared.
Setting the input’s opacity to 0 fixes this bug by hiding
the element from view, but still allowing it to be
interacted with. The input can safely be hidden because the
fake input gives the visual cue as to where the checkbox is
and what it looks like.
Bug referenced in #360

Set Checkbox input’s opacity to 0 to fix double border bug in legacy IE

---

src/components/settingBlock/settingBlockButtonWrapper.jsx

When the button is focused, give the Checkbox component an outline. The
outline cannot be added to the Checkbox component’s input when focused
because the input is being hidden with `opacity: 0` to fix a legacy IE
bug referenced in #360

Add focus state to checkbox in SettingBlockButtonWrapper

---

src/components/typeahead/styles.js

this style was being duplicated on profile since it already exists on the settingBlockWrapper

fix: remove typeahead border style

---

src/styles/colors.js

We use `#000` a lot for `box-shadow`. The alpha levels vary. This color should allow us to have a default and then adjust the alpha with `rgba`.

Add primary shadow color

---

src/components/flyout/index.jsx
stories/index.jsx

* Import `colors`, `zIndex` from styles; replaces settings.json
* Use `propTypes.style` to validate `style` prop
* Use `rgba` color utility instead of `rgb`
* Change z-index value to `popup`
* Adjust arrow up and down, top and bottom from `-5.5` to `-5`;
fixes visible hairline gap between arrow and menu container
* Change all shadows to use `shadowPrimary` color
* Add `arrowPosition` prop; allows up- and down-facing arrows
to be offset to the left or right by 28px instead of being centered

Update flyout component

---

src/components/bookmarkButton/index.jsx
src/components/icon/index.jsx
src/components/listButton/index.jsx
stories/index.jsx

Desktop views use a different icon than mobile views
BoomarkButton now accepts a prop `iconType` and its value can either be "default" or "alternate".
default: 
alternate:

Add alternate bookmark icons

---

src/components/listItemBookmark/index.jsx

`{visibility && entriesCount &&` was added to hide the meta data if the component was used for the "add new list" button. However, if `entriesCount` was 0, then the condition returned false and output a 0 to the screen.
I think it should be enough to check for `visibility` only because if the component is used for "add new list" button, it shouldn't have `visibility`. Also, we want to show "0 places" on the item if there are none, so it's ok if `entriesCount` is 0.

Only check visibility in ListItemBookmark

---

src/components/articlePreview/index.jsx
stories/index.jsx

Sometimes the content from the Wordpress API comes back with encoded
characters.

Allow setInnerHTML on ArticlePreview paragraph

---

src/components/listItemBookmark/index.jsx

Use numbers instead of strings for Heading props in ListItemBookmark

---

src/components/listItemBookmark/index.jsx

There are cases where we want the “mobile” style (small size) on
desktop. So media queries have been removed in favor of passing a prop
`large` to the component to apply “desktop” styles.

Refactor MQ styles for ListItemBookmark, add large prop

---

src/components/input/index.jsx
src/components/textarea/index.jsx
stories/index.jsx

* Deprecates `form/input.jsx` and `form/textarea.jsx`
* Accepts any valid attributes for `input` or `textarea` elements
* Textarea component can autogrow; use props `autogrow` and `maxLines`
* No more themes; pass in styles from design tokens to change height, font size, padding, etc.

Create new text input components

---

src/components/modal/index.jsx

Allow modal title to remain visible if showTitle prop is passed, otherwise "display: none" in desktop media query

fix: show modal title via bool prop

---

src/components/textarea/index.jsx

I think the purpose of the autogrow textarea is to all allow multiple line titles naturally. This prevents a user from adding newlines either intentionally or unknowingly.

Disable enter key in textarea when autogrow is true

---

src/components/modal/wrapper.jsx

currently if a user navigates away from a page while a modal is open, the scroll lock on the html stays in place so you can't scroll
this fixes the issue by listening to navigation and unMount events to remove the fixed window styles

fix: disable scroll lock off after navigate

---

src/components/bookmarkButtonAlt/index.jsx
src/components/iconRevealButton/index.jsx
stories/index.jsx

need to build a component like the bookmarkButtonAlt that can take any icon in (ie Share).
Built a lower level IconRevealButton that will take any icon and any string to work the same way as the bookmarkButtonAlt currently works, then rebuilt the bookmarkButtonAlt component using the new IconRevealButton;

fix: refactor bookmarkButtonAlt to use a lower level component

---

src/components/text/textAccent.jsx
src/components/text/textBodyArticle.jsx
src/components/text/textBodyArticleSmall.jsx
src/components/text/textBodySmall.jsx
src/components/text/textUppercase.jsx

change: Set "node" prop type for text components
Makes f.e. anchor child valid. Heading components already accept nodes.

Set node type for text components children

---

src/components/profileHeader/index.jsx

There is still an issue with the toggleReadMoreLink method. I wasn't able to get the correct lifecycle method working, so if you have no bio and then update your bio, and it's long enough that it needs the "read more" link, the link won't show up until a page refresh. This is because I'm not running `componentWillReceiveProps`. It's something I will keep looking into, but I wanted to get this fix up as it's broken on production.

Fix bugs in ProfileHeader

---

src/components/profileHeader/index.jsx

We don't want to show `http://` in the UI, but the href needs
it. The bug was caused by the assumption that `http://` would
always be there. The fix is just to remove `http://` and
then add it back in the href so it will always be there.

Make sure profile header URL has `http://` in href

---

src/components/avatarUpload/index.jsx

currently on mobile the native menu for adding a photo to the avatar upload allows you to also add video. this crashes the site/app. 
this pr limits file types to just images
fixes https://github.com/lonelyplanet/dotcom-profile/issues/401

fix: only allow photos to be uploaded via avatart uploader

---

src/components/profileHeader/index.jsx

urlParser was still trying to perform a `replace` function on the return value so I am returning an empty string instead of false for now

fix: return empty hostname from urlparser if server rendr

---

package-lock.json
package.json
src/components/profileHeader/index.jsx
src/components/profileIntro/index.jsx
stories/index.jsx
yarn.lock

* Use react-measure to create element query and allow component to control its own layout; replaces `alignment` prop which has been removed
* Create ProfileIntro component, which contains expand/collapse and markdown rendering; also uses react-measure to decide when to show "read more" link, which replaces `window.resize` and `componentDidMount` stuff

Update ProfileHeader layout

---

src/components/flightSearchWidget/index.jsx

moves arrow to be centered between departure and arrival locations

fix: make flight widget arrow centered

---

src/components/sectionHeader/index.jsx
src/components/text/textHeading.jsx
stories/index.jsx

This PR makes a few changes to the SectionHeader component.
* Replace media queries with react-measure. This allows for the component’s size to dictate its responsive styles instead of the window’s size. In turn, the component has been converted from functional to stateful because the dimensions provided by react-measure need to be handled within the component’s state.
* Remove containing `header` element. There is no reason for an extra container around the Heading component, so it has been removed.
* Use new TextHeading component and typography styles
* Change divider from `hr` to a `span`. Ideally, the divider would be build purely in CSS using pseudo elements; this change mimics that idea. 1. A pseudo element lives inside of it’s parent element, so the divider markup has been moved …

Refactor SectionHeader component

---

package-lock.json
src/components/pageHeader/index.jsx

narrative pageHeaders title links go to DN pages so this component needs to swap out react-router link for an `<a>` when a fully qualified url is provided

fix: allow pageHeader title to have external link

---

src/components/modal/wrapper.jsx

If a hash value is passed in, then on `componentDidMount`, the modal
will open when the URL contains the hash.
If a hash is present when the modal is closed, then the hash will be
removed from the URL via `history.pushState`.

Add hash prop to modal wrapper

---

src/components/modal/wrapper.jsx

This prop gives the option to disable the `no-scroll` module and allow
the parent window to scroll.
Allowing the parent window to scroll fixes a bug when a captcha is
loaded in a modal window and the captcha puzzle is sometimes pushed
off-screen, especially on mobile-sized screens. Without the `no-scroll`
module loading, the captcha puzzle can properly position itself.

Add enableWindowScrolling prop to ModalWrapper

---

src/components/video/videoPlaylist.jsx

Fixes a bug in copilot where height is 0 and playlist is not visible.

Let video playlist container height be auto

---

src/components/card/cardAnchor.jsx
src/components/card/cardImage.jsx
src/components/cardVideo/index.jsx
src/components/video/videoPlaylist.jsx
src/components/video/videoPlaylistWithSlider.jsx
src/components/video/videoPopout.jsx
stories/index.jsx

By default `VideoPlaylistWithSlider` cards and thumbnails will all control the player's source.
The `followVideoUrls` prop can be used (set to true) to tell the component that cards and thumbnails should redirect the user to the `/video` player page instead of changing the source of the in-page player.
Also fixed a bug with the duration not properly being set on the `VideoFeatured` component within the `VideoPlaylist` component, which was also causing a weird loading glitch -- now fixed.

feat: VideoPlaylistWithSlider.followVideoUrls prop added

---

src/components/cardShelfVideoSlider/index.jsx
src/components/video/videoSlider.jsx
stories/index.jsx

_Also, renamed VideoSliders `showArrows` to `arrows` to match the react-slick props._
The "Coverup" was a `div` that hung off the edge of the slider that was intended to match the page background.  It was meant to cover up incoming cards as the slider slid.
But, the slider itself now has an `overflow: hidden` around it and you can't see the cards that are sliding into view anyway.
But, the main purpose for fixing this was because this is what the 100% width slider looked like on mobile (notice the right margin along the page):

fix: Removed coverUp from VideoSlider

---

src/components/video/videoEmbed.jsx

Basically replaced usage of videojs private variables (variables that end with `_`) with non-private variables.
For example:
`this.player.textTracks()` returns a "text tracks" object  -- not a list.
`this.player.textTracks().track_` is assumed to be a private variable and isn't present on all browsers.  It's a list, but not reliable.
`this.player.textTracks()[0]` DOES work... so basically just wrote a wrapper around that.

fix: Cue points break on mobile safari

---

.babelrc
package-lock.json
package.json

This transpiles `Object.assign` for IE 11.

Transform Object.assign with Babel

---

package.json

This will help to fix errors `Invalid context ‘_radiumStyleKeeper’ of
type ‘StyleKeeper’` in apps that use Backpack

Make Radium a peer dependency

---

src/components/iconButton/index.jsx
src/components/video/videoEmbed.jsx

To reduce the bundle sizes of libraries that import backpack, we need to make sure to pull in individual pieces of lodash. Otherwise it will accidentally pull in the whole thing...

fix: Reduce lodash dependencies

---

package-lock.json
src/components/iconButton/index.jsx

This broke things when multiple "React trees" were being rendered on a single page and both were using IconButton -- they'd reuse each others element ids and cause conflicts.
Also, removed some PropType strictness.

Updated IconButton use of radiums Style component to use classes instead of element ids

---

src/components/cardShelfVideoSlider/index.jsx
src/components/video/videoSlider.jsx
stories/index.jsx

Added the following properties to `VideoSlider` (for upcoming new player UI)
`slidesToShow` - override default media-query-driven slide count with hardcoded numerical pixel value
`mqSlidesToShow` - media-query-driven slide counts (This defaults to a maximum of `4`, but if `slidesToShow` is specified, `mqSlidesToShow` is completely ignored.
`draggable` - enables dragging (really it's just scrolling)
`cellSpacing` - override default media-query-driven cell spacing with hardcoded numerical pixel value
`childStyles` - any overrides to child/slide styles

VideoSlider draggable

---

src/components/bookmarkListMenu/index.jsx
stories/index.jsx

Allows for a custom button element to be used instead of the icon buttons.
We will be able to build the share menu like designed on the new POI pages.

Add button prop to bookmark list menu component

---

stories/index.jsx

we don’t use shorthand there because if you need to change one side, radium throws an error

fix: remove shorthand padding to be consistently explicit

---

src/components/button/index.jsx

fix: spread rest of props over button component

---

src/components/video/videoPopout.jsx

Apparently IE 11 doesn't recognize `height: initial`

fix: popout player stretches entire height of browser window on IE 11

---

src/components/spotlightZone/index.jsx

fix: SpotlightZone flows off of page on IE 11

---

src/components/overlay/index.jsx

https://lonelyplanet.atlassian.net/browse/DOT-314
create and cancel buttons are pushed off screen in iOS, adding `height: 100vh` restricts the overlay to the viewport

fix: DOT-314 add height to overlay to prevent going off screen in iOS

---

src/components/bookmarkListMenu/index.jsx

fixes menu currently popping under photo gallery

fix: DOT-316 add default z-index to share menu

---

src/components/staticMap/index.jsx
stories/index.jsx

Added prop for zoom level for static mapbox component. I need to be able to customize the zoom level  when adding a static map to the Best in campaigns so get a broader view of the location.

feat: add prop for zoom level on static mapbox component

---

src/components/multiStep/multiStepWrapper.jsx

This makes it possible to server side render the sign in form at the password prompt step after users enter an incorrect username or password. 
This will be used for Alexa's oAuth client, because they don't display errors sent to the callback handler.

Add ability to set the initial step of the multistep wrapper

---

src/components/socialLoginButton/index.jsx

This should resolve this warning in the console.
> Warning: Invalid argument supplied to oneOf, expected an instance of array.

fix: Pass an array to PropTypes.oneOf instead of multiple arguments

---

src/components/video/videoEmbed.jsx

Moved the unique ID from `className` to the `id` attribute on the video element.

fix: Give the video element a unique ID instead of className

---

package-lock.json
package.json

there is an issue on wp-travelnews related to the react-stickynode library. Updated to the newest version resolves this
https://lonelyplanet.atlassian.net/secure/RapidBoard.jspa?rapidView=2&modal=detail&selectedIssue=DOT-396

fix: update sticky dependency

---

src/components/reviewedBadge/index.jsx

Allows the icon to size along with the text and maintain the correct proportions.

Make ReviewedBadge icon size relative

---

src/components/ad/index.jsx
stories/index.jsx

Allow children to be descendants of Ad, so that it may be used as a style wrapper for Ad calls.
As an example, using `<Ad>` to wrap `amp-ad` components to have consistent styling and labeling.

feat: allow ad children

---

src/components/spotlightZone/index.jsx
src/components/video/videoEmbed.jsx
src/components/video/videoPlaylist.jsx
src/components/video/videoPlaylistWithSlider.jsx
stories/index.jsx

Video Playlists should only show the video title in it's overlay.   Previously, the video's description and a slider with related locations would be shown, but that alongside the video playlist is just too much text all over the place -- this is just an effort to clean things up visually for the user.

feat: VideoPlaylist to show less overlay text

---

src/components/modal/index.jsx
src/styles/timing.js

react-modal requires a number be passed in for the timeout, not a string

fix: add numbers to timing for modal closeTimeoutMS proptype error

---

src/components/video/videoEmbed.jsx
stories/index.jsx

It looks like this:
I just never put it into backpack before because this functionality was only needed in rizzo-next at the time.

feat: added muted overlay via videojs-lp support

---

src/components/staticMap/index.jsx

pinterest hover can prevent default anchor click action from firing, this tag stops pinterest from targeting map images

fix: prevent pinterest hover widgets from hijacking staticMap links

---

src/components/thumbnailListItem/index.jsx
src/components/video/videoPlaylist.jsx
src/components/video/videoPlaylistWithSlider.jsx
stories/index.jsx

- New `theme` prop on `VideoPlaylist` and `VideoPlaylistWithSlider` ( can be set to `light` (default) or `dark`)
- `heading` prop on both those components is now optional
- Added `active` as a possible value for the `theme` prop on `ThumbnailListItem` component
- Updated borders and padding on playlist components as well

feat: added light theme to video playlist components

---

src/components/iconButton/index.jsx
stories/index.jsx

Also, `div` is now a potential container element for `IconButton` (if it has no `onClick` or `href` specified).  This is so it can be used within a button or link without having nested buttons/links.

feat: added borderwidth and bordercolor props to iconbutton

---

src/components/video/videoEmbed.jsx
src/components/video/videoPlaylist.jsx
src/components/video/videoPlaylistWithSlider.jsx

Also:
- Added `onLoadStart` prop to bind handlers to when a video loads into the player
- Added `poster` prop since it's a standard `video` attr that was missing (and i needed it for something)
- Removed `centered` from the `vjsLP` prop because it's not an option on the `videojs-lp` plugin any more

feat: updated videoembed to apply video element attrs on initial render

---

src/components/video/videoPopout.jsx

Some LP pages size their players dynamically based on the aspect ratio of the device screen.  The old styling used for the popout player was too dependent on percentages of it's parent and doesn't size itself correctly on these pages.
Example page of a non-16:9 player with bugs in the popout player's size/dimensions: https://www.lonelyplanet.com/video/how-to-spend-24-hours-in-lisbon-portugal/v/vid/895

fix: updated videopopout to stay 16:9 independent of parent container

---

CHANGELOG.md
package-lock.json
package.json

I think that branch protection broke the automated workflow of pushing & releasing this.
Just need an approval.

chore: release 4.88.1

---

package-lock.json
package.json
src/components/newsletter/index.jsx

Imports `lp-analytics` and uses it to push a very simple event to the dataLayer whenever a newsletter subscription occurs.
Note that inclusion of `gtm.js` (and the actual tracking activity that its inclusion establishes) is up to the host codebase; this will only ensure that events are pushed to the `dataLayer` (which will be created if necessary). In the absence of `gtm.js` it's a plain ol' JS array. In the presence of `gtm.js` it's a patched array whose `.push` method also sends events along to gtm.

feat: track newsletter subscriptions per AP spec

---

package-lock.json
package.json

I think this is breaking `destinations-next` builds.
Jenkins keeps throwing `Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose' in '/mnt/workspace/destinations-next-branch-test/node_modules/react-measure/dist'`.
Seems like the same issue [cropped up](https://github.com/meteor/meteor/issues/10128#issuecomment-410523377) in several big-name JS projects this August, when Babel 7 was released.
And `react-measure` [upgraded to Babel 7](https://github.com/souporserious/react-measure/commit/14e725e496fb0ac34f0ada7b011d134d4ee0872d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L50) in a commit that was released with its version 2.2.
[`react-measure`](https://www.npmjs.com/package/react-measure/v/2.2.0) 2.2 was published 4 days ago at time of writing, which …

fix: lock version of react-measure

---

src/components/articlePreview/index.jsx
stories/index.jsx

Added optional prop for image alt text to the ArticlePreview component. This will help aid in accessibility of images.

fix: add optional prop for image alt text

---

src/components/navigation/navigation.jsx

"position: sticky;" needs an extra prefix that even autoprefixer doesn't set currently. Adding it manually here so that the "sticky" feature for the navigation component will work in Safari.

fix: add webkit prefix for sticky nav

---

src/components/photoGallery/index.jsx
src/components/photoGallery/styles.js
stories/index.jsx

* Inline SVG icons for close and arrow buttons; some environments seem
to block the assets from loading, so inlining gets around this issue.
Also, `!important` was added to the `background-image` declaration
because the plugin’s default styles can override backpack-ui generated
styles depending on the build process.
* Add `uiOptions` object; this ensures only the required controls
(close, next, prev) are included.

Update PhotoGallery component

---

src/components/form/daterange.jsx
stories/index.jsx

I spent some time Friday debugging `backpack-ui` and `destinations-x` styles before figuring out that the process described in this PR is what I needed to do to get everything working properly.
This documents the requisite setup for future devs.
As written in the comment, I figure that having the `DeveloperNote` displayed in `storybook` will more effectively propagate the message than would including it in the `README` (and there's generally all that blank space in storybook anyway, right?)
That said, I don't know of any precedent for doing this in storybook, so please let me know if there are any thoughts/concerns about the approach.

chore: add note in storybook about DateRange setup

---

src/components/price/index.jsx

`Price` only knows symbols for these four currencies. If something else gets passed in, it winds up rendering `undefined` where the symbol should go.
In lieu of thinking further about desired behavior here (In practice this evidently hasn't been an issue), I'm just going to have React bark at us if anything gets passed in that the component doesn't know how to handle.
(I was originally doing this in `destinations-x`, but it belongs here).

chore: add proptype enum for currency

---

src/components/form/select.jsx

Updates the proptypes of the component to reflect what it actually accepts, and allows for `className` to be added.

chore: maintain select component

---

package-lock.json
package.json
src/components/articlePreview/index.jsx
stories/index.jsx

Adding click event tracker for the article preview component. By adding this, in each repo that this component is being used, we can add a name and id to the event tracker so that these are viewable in GA. Per Kristen and Analytics Pros, we should use "Promotion Click" for this type of even tracking.
@johnwquarles can you please confirm that this is working as it should? I was using that chrome extension but it appears that it doesn't work on localhost, or perhaps I am missing something. Can you please let me know the best way to test this?

fix: add analytics click trackers to article preview component

---

spec/utils/createQAHook.spec.js
src/components/button/index.jsx
src/components/navigation/navigation.jsx
src/components/navigation/navigationTab.jsx
src/utils/createQAHook.js
stories/index.jsx

Allowing our automation to become less brittle to updating changing classes/ids. These custom data attributes will be available for QA Engineers to update for automation (integration/E2E) and empower the FE developers to change classes/ids without concern.
See: https://blog.kentcdodds.com/making-your-ui-tests-resilient-to-change-d37a6ee37269
This may not be the last PR regarding data hooks but I wanted to get the pattern passed before peppering it where it makes the most sense (most actionable elements [click, link, nav, et. al]) For this PR, just button and nav were touched.

feat: add custom data attributes for automation purposes

---

CONTRIBUTING.md

the contributing.md specifies to "Capitalize the subject line" (e.g. `fix: Summarize changes in 50 characters or less`)
but if you do it throws this error:
```
✖   subject must not be sentence-case, start-case, pascal-case, upper-case [subject-case]
✖   found 1 problems, 0 warnings
```
This will change the readme to match our LP convention being all lowercase per https://www.conventionalcommits.org/en/v1.0.0-beta.2/#specification

fix: change list of core contributors and capitalization rule

---

package-lock.json
package.json
src/components/articlePreview/index.jsx
src/components/newsletter/index.jsx
src/utils/analytics.js

Inclusion of `lp-analytics` as a dependency here is increasing the bundle size of `dotcom-frontend`.
This PR will remove it, and add some backpack-specific logic in its place.
Having application-specific analytics logic happening in every application is the problem `lp-analytics` was created to _solve_, but I think that in the end this approach is fine because:
1. Backpack-ui will be deprecated eventually
2. All the new analytics stuff will be happening in `dotcom-frontend` (eventually).
3. There isn't really that much of it happening here yet anyway.

chore: remove lp-analytics, reimplement what it was doing

---

src/components/tallCarousel/index.jsx

Fixes issue where react-slick classes are overriding our custom arrows for the TallCarousel.

fix: update prev/next button on tallCarousel

---

src/components/tooltip/index.jsx
src/libs/react-motion-ui-pack/Transition.jsx
src/libs/react-motion-ui-pack/config-to-style.js
src/libs/react-motion-ui-pack/from-RM-styles.js
src/libs/react-motion-ui-pack/get-prefix.js
src/libs/react-motion-ui-pack/is-element.js
src/libs/react-motion-ui-pack/special-assign.js
src/libs/react-motion-ui-pack/to-RM-styles.js

This folder needs to be nested in src so that it also gets compiled by
Babel when it hits the dist folder, otherwise it can't always be
imported.

fix: compile motion ui pack library folder

---

src/components/cardBook/index.jsx
stories/index.jsx

Add a prop to show/hide the menu(share, preview, download) on the cardBook component for the kids site.

fix: update cardBook to conditionally show menu

---

src/components/breadcrumbs/index.jsx

fix: updated line height on breadcrumbs

---

src/components/shareMenu/shareSettings.jsx
stories/index.jsx

WhatsApp sharing through the `ShareSettings` component now uses `api.whatsapp` url to share when on non-mobile devices.  This is what the `VideoInfo` component already does and this is what the social share components in `rizzo-next` already do as well.
- Added `mobile` prop rather than using `MobileUtil.isMobile()` because that's how other backpack components work.
- WhatsApp sharing is now opened in new window now because before, it'd take the user off of LP.com whereas all the other social media urls open in a popup window or new tab.
**TESTING:**
**Desktop users with WhatsApp installed:**
1. Uses `api.whatsapp` url
2. Opens "send to whatsapp" popup
3. Opens WhatsApp desktop app.
**Desktop users without WhatsApp installed:**
1. Uses `api.whatsapp` url
2. Opens "send to whatsapp" popup …

fix: changed ShareSettings WhatsApp url for desktop

---

src/components/shareMenu/shareSettings.jsx
stories/index.jsx

**WhatsApp:** Only uses the `api.whatsapp.com` url now as it works on both desktop and mobile, simplifying the component (no need for `mobile` prop).  It also has better UX for users on mobile who don't have the app installed.
**Reddit:** Now includes the share text along with the url
**Facebook:** Uses the documented share url here (https://developers.facebook.com/docs/sharing/reference/share-dialog) which allows us to pass in our facebook app id.
**Facebook Messenger:** Uses our facebook app id now

feat: updated share urls for all networks under ShareSettings component

---

package-lock.json
package.json

vulnerability reported by Rob: https://www.cvedetails.com/cve/CVE-2019-11358/
“There should be no compatibility issues if upgrading from jQuery 3.0+" from https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/ so we should be ok.

bump jquery

---

src/components/video/videoEmbed.jsx

[`ChildNode.remove()`](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove#Browser_compatibility) doesn't work in IE11 so I've updated this to use `parentNode.removeChild()` instead.

fix: use parentNode.removeChild() instead of remove() for IE 11

---

src/components/photoGallery/styles.js

**1.** z-index increased to `2000` (same z-index as our site header in `dotcom-frontend`) so that our header doesn't appear over the photo gallery overlay.  react-photoswipes default z-index is `1500`.  This isn't really a noticeable problem because the clickable photos on our news gallery pages are far enough down the page that you never see that the site header is on top of the photo gallery.
**2.** Fixed captions having a semi-transparent black background on mobile.
**3.** PhotoGallery navigation arrows and the close button in the upper right weren't appearing.
They were most likely working at one point before the majority of browsers updated themselves to more strict standards:
Two changes:
1. For IE support: Needed to replace `;utf8,` with `;charset=utf8,`.
2. The SVG path needs to …

fix: PhotoGallery CSS updates

---

src/components/newsletter/index.jsx

`key` props have been added to the `<a>` elements in the `legalOptInLabel` array to prevent this warning in the console.
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `Newsletter`. See https://fb.me/react-warning-keys for more information.
```

fix: added key prop to <a> tags

---

src/components/video/videoEmbed.jsx

https://lonelyplanet.atlassian.net/browse/ENG-58
Summary: If a pre-roll attempts to play immediately following a previous pre-roll, there is sometimes a race condition issue that comes up that throws the player into a confused state:
- Both the pre-roll and the video will play at the same time
- You won't be able to see either of them
- You'll be able to hear the video, while not being able to hear the pre-roll
The console will print something like this:
`VIDEOJS: WARN: Unexpected startLinearAdMode invocation (Preroll)`
I've only been able to reproduce this on Firefox.
This bug is in discussion here: https://github.com/googleads/videojs-ima/issues/796
But in short, 
```
The bug occurs when you try to load a pre-roll ad that takes more than the time specified in the prerollTimeout setting …
```

fix: video recover from faulty ad setup

---

src/components/form/textarea.jsx
src/components/settingBlockTextArea/index.jsx

see https://lonelyplanet.slack.com/archives/C026V0UT3/p1585150833000400
Hannah Horn reported:
"It seems that there might be a bug which is stopping users from being able to update their LP profile bio/intro - @john falkum and I tested this and we were also both unable to edit the Intro section. I can click in the box but when I try to type anything, it doesn't work :confused:. I am still able to edit and save a user's bio from within the auth/luna part of a user's profile."

fix: text area onFocus

---

src/components/link/index.jsx

Problem was introduced here: 
https://github.com/lonelyplanet/backpack-ui/commit/ceada46f075787933343799f74902e80d233c25a#diff-9e7d4605239820b84fbe18a8dc471ad28e4c829b4ef712f22ce25802dfc638e3R18
React-router doc saying it's `Link` component handles standard props just fine: https://reactrouter.com/web/api/Link/others
The props for the `Link` component were using a spread to pass any remaining props into the underlying `a` tag, but only for internal links.
This created a problem because some components rely on styling the underlying `a` tag.  This was breaking padding and absolute positioning of children. 
Before (notice horizontal padding issue between image and text -- the image is wrapped in a `Link` component ):
After:

fix: props not being passed to Link component when using relative url
