package.json

settings.json file was not being copied from src to dist which caused an error when importing the components.

Copy settings to dist, bump version

---

package.json

Will build and deploy storybook to a `gh-pages` branch.

Add a gh-pages build

---

package.json
src/components/container/index.jsx

Experiments with styled-components

Add container component

---

package.json

Version 1.0.0-alpha-9

---

src/components/button/index.jsx
src/components/form/input.jsx

we are passing nested media query objects to the custom styles prop. needed to add object to accepted props types

update propsTypes to get rid of warnings

---

package.json
src/components/button/index.jsx
src/components/form/input.jsx

bump up version of rizzo and fix the prop type warning once and for all 🎉

update props / update radium

---

src/components/interactiveMap/index.jsx
src/components/interactiveMap/styles.js

- Add max-width 100% to container
- Fix some linting errors by setting some methods to static and
re-ordering source order of methods
- Add `style` prop for CSS overrides

Update InteractiveMap component

---

src/components/iconCallout/index.jsx

not exactly sure what is happening here, but taking it out fixes the issue on ie11. 
Feel free to make suggestions on the best way to handle this.

fix article list item width

---

src/components/iconCalloutGroup/index.jsx

resolves https://github.com/lonelyplanet/copilot/issues/85

update iconCalloutGroup styles for homepage design

---

src/components/sightsListItem/index.jsx

fix link for sights list item

---

src/components/interactiveMap/index.jsx
src/components/sightsListItem/index.jsx

adds hooks for hover into sight list item and adds the ability for a prop to trigger modal popup on map

add mouse events to sight list

---

package.json
settings.json
src/components/calloutLink/index.jsx
src/components/categoryLabel/index.jsx
src/components/featuredArticle/index.jsx
src/components/featuredCallout/index.jsx
src/components/featuredSectionHeading/index.jsx
src/components/gradientOverlay/index.jsx
src/components/heroImageContainer/index.jsx
src/components/hideAtBreakpoint/index.jsx
src/components/listItemNews/index.jsx
src/components/listItemThumbnail/index.jsx
src/components/promotedGuidebook/index.jsx
src/components/sectionalNav/index.jsx
stories/index.jsx

- ListItemThumbnail
- ListItemNews
- PromotedGuidebook
- CategoryLabel
- CalloutLink
- HideAtBreakpoint
- FeaturedCallout
- FeaturedSectionHeading
- GradientOverlay
- HeroImageContainer
- FeaturedArticle
- SectionalNav (with dependencies)

Add new components

---

src/components/featuredCallout/index.jsx

Makes the font color white for CategoryLabel and CalloutLink

Fix up styles for FeaturedCallout components

---

src/components/author/index.jsx
src/components/authorName/index.jsx
src/components/italicText/index.jsx
src/components/newsArticleAuthor/index.jsx
src/components/timestamp/index.jsx
stories/index.jsx

Create components to build news article author

---

.storybook/addons.js
package.json
src/components/heading/index.jsx
stories/index.jsx

storybook-addon-knobs allows for props to be changed within storybook UI

Install storybook-addon-knobs, update storybook

---

src/components/bookmark/index.jsx
stories/index.jsx

- Fix rendering, styles
- Add `style` prop
- Remove `center`, `align` props; positioning can be passed in via `style` prop

Clean up bookmark component

---

src/components/bulletDescription/index.jsx
src/components/textBubble/index.jsx
src/components/thumbnailListItem/index.jsx
src/utils/icon.jsx
stories/index.jsx

adds list item component with thumbnail that is needed for lp.tv

list items w/ thumbnail

---

src/components/scrollIndicator/index.jsx
src/utils/icon.jsx
stories/index.jsx

Adds mouse with arrow icons to indicate to the user to scroll

add scroll indicator from homepage

---

src/components/iconCallout/index.jsx
src/components/paginatorButton/index.jsx
src/components/thumbnailListItem/index.jsx
src/utils/icon.jsx
stories/index.jsx

Updates to iconFromString util and use it for some components

---

src/components/iconButton/index.jsx
src/components/mapMarker/index.jsx
src/components/moreLink/index.jsx
src/components/rating/index.jsx
src/components/shareMenu/item.jsx
src/components/socialIconButton/index.jsx

Missed a few components that were still using `React.createElement(Icon)`

Replace React.createElement with iconFromString

---

src/components/tabbedNav/index.jsx
stories/index.jsx

Create TabbedNav component

---

src/components/socialLoginButton/index.jsx
stories/index.jsx

takes icon, text, action. 
Can be configured for any social network login

adds social login button

---

src/components/card/cardActionIcon.jsx
src/components/card/cardAnchor.jsx
src/components/card/cardDescription.jsx
src/components/card/cardDescriptionPoster.jsx
src/components/card/cardImage.jsx
src/components/card/index.jsx
src/components/cardVideo/index.jsx
src/components/tileVideo/index.jsx
src/components/tileVideoPoster/index.jsx
stories/index.jsx

Includes a video tile with poster-sized image

Update card components, create new video tile components

---

src/components/segment/index.jsx
src/index.js

adds segment which from copilot that handles vertical spacing and border between sections

add segment component

---

src/components/sectionHeader/index.jsx
src/components/spotlightZone/index.jsx

SpotlightZone also needed container component and updated styles to match design comp.

Add style prop to SectionHeader, SpotlightZone components

---

src/components/sectionHeader/index.jsx
stories/index.jsx

plugs in a theme system for section heading and adds a dark theme

add theme to seciton heading

---

package.json
src/components/cardVideo/index.jsx
src/utils/time.js
stories/index.jsx

takes unit of time in milliseconds or seconds and converts to a human readable time

add function to parse video duration as a number value

---

src/components/masthead/index.jsx

let masthead just be the height of its content

adjust regular masthead

---

src/components/card/card.jsx
stories/index.jsx

quick fix for card sizing. we will need to revisit this with a more flexible / permanent solution

add fixed width and minHeight to card for short term fix of card size

---

src/components/card/card.jsx

Remove shadow and scale from hover effect; request from Craig

Subdue card hover effect

---

src/components/cardShelfVideoSwiper/index.jsx

render pagination buttons based on active slides and slide count

conditionally show and hide pagination buttons

---

src/components/slide/index.jsx

starts scaling size later and bumps up font size at max

bump up the size of the heading text

---

src/components/videoEmbed/index.jsx

- Renamed autoPlay to autoplay
- Fixed brief unstyled player controls glitch
- Added onEnded parameter

VideoEmbed updates

---

src/components/mastheadSlider/index.jsx

Trying to fix the masthead

---

src/components/photoGallery/index.jsx
src/components/photoGallery/styles.js
stories/index.jsx

Will be used in the travel news app.
I don't love how I'm pulling in the styles, but it was the quickest way to get them in. Any thoughts?

Add photo gallery from POIs, articles

---

src/components/photoGallery/styles.js
stories/index.jsx

These commits didn't get applied or merged with #100

Update PhotoGallery component CSS

---

src/components/cardVideo/index.jsx

empty array still evaluates to true so need to check length to make sure div doesn't appear
closes https://github.com/lonelyplanet/dotcom-video/issues/92

only show description div if description exists

---

src/components/tag/index.jsx
src/components/tagList/index.jsx
stories/index.jsx

Update styles, use `children` prop

Update tag components [breaking]

---

src/components/avatar/index.jsx

Reflects sizes used in latest profile design comps

Update avatar sizes, use propTypes.style

---

src/components/toast/index.jsx
src/index.js
src/styles/colors.js
stories/index.jsx

Create Toast notification component

---

package.json
src/components/card/cardAnchor.jsx
src/components/card/cardImage.jsx
src/components/cardShelf/cardShelfHeader.jsx
src/components/link/index.jsx
src/components/slide/index.jsx
src/components/spotlightZone/index.jsx
src/components/thumbnailListItem/index.jsx

this `Link` tag will decide on rendering an `<a>` or react-router `<Link>` based on the url string that is passed through.

add custom link tag to swap <a> for <Link>

---

package.json
src/components/card/cardAnchor.jsx
src/components/cardShelfVideoSwiper/index.jsx
src/components/cardVideo/index.jsx
src/components/gradientOverlay/index.jsx
src/components/heading/index.jsx
src/components/heroImageContainer/index.jsx
src/components/link/index.jsx
src/components/mastheadSlider/index.jsx
src/components/newsArticleAuthor/index.jsx
src/components/sectionHeader/index.jsx
src/components/tallCarousel/index.jsx
src/components/tileVideo/index.jsx
src/components/typeSelector/index.jsx
src/components/watchLater/watchLaterEmptyList.jsx
src/components/watchLater/watchLaterModal.jsx
stories/index.jsx

moves modal close state outside of component so it can be handled by props through a redux store
fixes warnings

modal close handler

---

src/components/cardVideo/index.jsx
src/components/modalContent/modalContentWatchLaterList.jsx
src/components/slideTall/index.jsx
src/components/watchLater/watchLaterList.jsx
src/components/watchLater/watchLaterModal.jsx

- TallCarousel slides now use react-router Link to keep LP.TV channels pages from refreshing
- Added removeAll property to WatchLaterModal so that different functions can be bound to the 'Clear All' button than the 'X' buttons on each modal tile

LP.TV needs

---

src/components/modalContent/modalContentWatchLaterList.jsx
src/components/watchLater/watchLaterModal.jsx

Resolves lint errors from #177

Remove trailing whitespace

---

src/components/slide/index.jsx

adds option to have a full overlay on the slide component for slides that need more contrast

update: add fulloverlay options to Slide component

---

src/components/gridRow/index.jsx

This allows us to pass media queries to the component

Add radium to GridRow component

---

src/components/modalContent/modalContentSocialAuth.jsx

fix: change the path for social login buttons

---

src/components/moreLink/index.jsx

related p/r: https://github.com/lonelyplanet/copilot/pull/275

add optional target='_blank' switch

---

src/styles/colors.js

Constants allow alpha channel manipulation on colors; constants
are exported as a default object like before.

Refactor colors, use constants to define values

---

src/components/videoEmbed/index.jsx

Added dynamic resizing of lower third overlay to fit dynamically sized lower thirds
Note: It is unlikely that static-sized lowerthird ads will orientate themselves correctly.  We are taking this one step at a time.

Added dynamic resizing of lower third overlay

---

src/styles/colors.js

Change linkPrimaryHover alpha, add textOverlay

---

src/components/slide/index.jsx
src/components/videoEmbed/index.jsx

Removed display:none from ad placement in Slide Component

---

src/components/form/heightExpander.jsx
src/components/settingBlock/index.jsx
src/components/settingBlock/settingBlock.jsx
src/components/settingBlockAction/index.jsx
src/components/settingBlockInput/index.jsx
src/components/settingBlockTextArea/index.jsx
stories/index.jsx

fixes imported file names
fixes textarea height on mount
fixes input values being able to be passed through

setting block fixes

---

src/components/tabs/index.jsx
src/components/tabs/tab.jsx
src/components/tabs/tabPanel.jsx
src/components/tabs/tabs.jsx
stories/index.jsx

This PR takes the recently created Navigation components and builds a tabbed content component around them. These components will deprecate the TabbedNav component.
#218, #226

Create tab components

---

src/components/avatar/index.jsx

This allows the image to fit the defined space while retaining its proportions

Add object-fit property to avatar image

---

src/components/container/index.jsx

To provide styling hooks when building layouts

Add ID and classname props to container component

---

src/components/flag/index.jsx
stories/index.jsx

Create Flag component

---

src/components/tabs/tabs.jsx

Allow content to dictate spacing

Remove style from tabContent wrapping div

---

package.json

Attempt to fix failing production build due to recent changes to
dependencies in the react-slick package

Update react-slick to 0.14.10

---

src/components/form/input.jsx
src/components/form/textarea.jsx
src/components/settingBlockInput/index.jsx
src/components/settingBlockTextArea/index.jsx
stories/index.jsx

adding an optional value prop allows for these form inputs to be wrapped in higher order components if they need their values to be controlled values.

update: add value and other props to pass through to form inputs

---

src/components/profileHeader/index.jsx
src/components/tagList/index.jsx
stories/index.jsx

adds wrapper around tagList to limit number of visible tags

feat: add taglist limiter

---

src/components/socialLoginButton/index.jsx
stories/index.jsx

- Update CSS
- Use typography styles
- Require specific iconName
- Remove iconColor prop; use colored version of icons
- Use {…props} to allow any valid HTML properties, i.e., class, id, aria, etc

Update SocialLoginButton to match updated design

---

spec/utils/typography.spec.js
src/styles/typography.js

Update line height for headings

---

src/components/tag/index.jsx

- Add outline styles to focus state
- Change border and hover background colors
- Add max-height
- Move typography styles to end of default style object

Update styles for Tag

---

src/components/socialIconButton/index.jsx
src/styles/colors.js

- Remove/replace lodash dependency
- Add classname and ID props
- Use styles
- Add outline to focus state

Update SocialIconButton, add color variable for Twitter

---

src/components/socialShare/index.jsx

Add className to button in SocialShare

---

spec/utils/typography.spec.js
src/components/breadcrumbs/index.jsx
src/components/heading/index.jsx
src/components/text/textHeading.jsx
src/styles/typography.js
src/utils/propTypes.js
src/utils/typography.js
stories/index.jsx

Replaces and deprecates book weight
Closes #214

Use regular weight for Benton Sans

---

src/components/button/index.jsx
stories/index.jsx

Went in and added a gray button color style and updated the colors to use new color settings.

update : added gray button style and updated colors

---

src/components/toast/index.jsx

update-updated the icon marg

---

src/components/avatar/index.jsx

Add 24 to sizes for Avatar component

---

src/components/avatarMarker/README.md
src/components/avatarMarker/index.jsx
src/index.js
stories/index.jsx

Create AvatarMarker component

---

package.json

Update license in package.json to MIT

---

src/components/disclaimerText/index.jsx

Allows the link color to be default (blue) and bold.

Change link style for DisclaimerText

---

src/components/disclaimerText/index.jsx

Change color and decrease font size

Update DisclaimerText styles

---

src/components/ad/index.jsx

ad is sometimes hanging outside of the parent container. 
these style changes remedy the issue

fix: change ad padding to not let ad break out of container

---

package.json
yarn.lock

Fixes JavaScript error `Uncaught TypeError: Cannot read property
'getAttribute' of null` when trying to change values of knobs

Update storybook to 2.35.3

---

src/components/newsletter/index.jsx
stories/index.jsx

Replaced hardcoded text with default props. Updated the default text and fixed typo.

update: Update typo in newsletter component

---

src/components/text/textAccent.jsx
src/components/text/textBodyArticle.jsx
src/components/text/textBodyArticleSmall.jsx
src/components/text/textBodySmall.jsx
src/components/text/textSuper.jsx
src/components/text/textUppercase.jsx

This allows for valid HTML attributes to be passed onto the components

Spread props on text components

---

src/components/dialog/README.md
src/components/dialog/index.jsx
src/index.js
stories/index.jsx

Create Dialog component

---

src/components/gridColumn/index.jsx

Fix typo in gridColumn for gutterPosition so that the props can be passed properly.

Fix: Update gridColumn

---

src/components/modalContent/modalContentSocialAuth.jsx

https://github.com/lonelyplanet/dotcom-profile/issues/69

Add link to account help in social auth component

---

src/components/multiStep/README.md
src/components/multiStep/index.jsx
src/components/multiStep/multiStep.jsx
src/components/multiStep/multiStepWrapper.jsx
src/index.js
stories/index.jsx

Create Multi-step component

---

src/components/watchLater/watchLaterModal.jsx

630px translates to 6 grid columns

Set width of WatchLaterModal to 630px

---

src/styles/colors.js

Make bgDark 96% black

---

package.json
src/components/modalContent/modalContentMagicLinkForm.jsx

@thomasthesecond just has the logic I need in there, feel free to rename anything, style anything move anything. 
I really just need the onSubmit handler to pass through. 
Thanks!

feat: add magic link form component for sign in modal

---

yarn.lock

- prop-types
- react-validate-form
From #317

Update yarn.lock with new dependencies

---

src/components/disclaimerText/index.jsx

* Move scoped styles to constant
* Remove dangerouslySetInnerHTML to render children

Update DisclaimerText component

---

src/components/modal/index.jsx

Updates for profile authentication

Update Modal component

---

src/components/toast/README.md
src/components/toast/index.jsx
stories/index.jsx

Adds specific styles and icon based on new `type` prop, which can be one of "alert", "error", "neutral" or "success". `type` prop replaces `color` and `icon` props.

Update Toast component

---

.storybook/addons.js
.storybook/config.js
package.json
stories/index.jsx
yarn.lock

Hello !
First: Amazing storybook, we love it! 
We have your storybook as a demo on https://storybook.js.org because we think it's a pretty storybook and a showcase of how nice a storybook instance can be.
This PR migrates your storybook to the latest version : `3.0.0`.
Hope you like it
♥️

UPGRADE to storybook 3.0.0

---

src/components/socialShareContainer/index.jsx

This allows the Twitter username to be changed if desired
https://github.com/lonelyplanet/wp-travelnews-frontend/issues/318

Add via prop to SocialShareContainer

---

.storybook/common.css
stories/designTokens/colors.jsx
stories/designTokens/dimensions.jsx
stories/designTokens/fontSize.jsx
stories/designTokens/fontWeight.jsx
stories/designTokens/fonts.jsx
stories/designTokens/index.jsx
stories/designTokens/lineHeight.jsx
stories/designTokens/mediaQueries.jsx
stories/designTokens/spacing.jsx
stories/designTokens/timing.jsx
stories/designTokens/token.jsx
stories/designTokens/zIndex.jsx
stories/index.jsx

Design tokens display the keywords and values that are contained within `styles`. This should help designers and developers share a common language and visualize the styles that are currently in use.

Add design tokens story

---

src/components/interactiveMap/index.jsx

resolves https://github.com/lonelyplanet/backpack-ui/issues/202

fix: icon color on interactive map being overwritten

---

src/components/toast/README.md
src/components/toast/index.jsx
stories/index.jsx

- Change types to "error", "info", "success", "warning"
- Change onClick to onClose
- Add close button
- Add title

Update Toast design

---

src/components/multiStep/multiStepLogin.jsx
src/components/spotlightZone/index.jsx

closes https://github.com/lonelyplanet/backpack-ui/issues/346
also fixed a linting issue in the spotlight component

fix: update disclaimer based on type of authentication

---

src/components/modalContent/modalContentLegacyLoginForm.jsx

closes https://github.com/lonelyplanet/react-validate-form/issues/2

fix: remove form submission hijack

---

src/components/navigation/navigation.jsx

Closes lonelyplanet/dotcom-profile#104...

fix: change navigation zindex to 99 to stay behind public profile dropdowns

---

CONTRIBUTING.md

With master now being a protected branch, only admins can create releases now and forever.

Add release guide to contributing doc

---

src/components/modalContent/modalContentLegacyLoginForm.jsx
src/utils/validations.js

allows legacy user to sign in via username or email

fix: allow legacy user to use both email/username to login

---

src/hoc/clickOutside/README.md
src/hoc/clickOutside/example.jsx
src/hoc/clickOutside/index.jsx

Enhances a React component with a Higher Order Component that provides click outside detection

Add HOC to detect outside clicks

---

src/components/userListAuthor/index.jsx
src/index.js
stories/index.jsx

Create UserListAuthor component

---

src/components/shareMenu/index.jsx

Use HOC for click outside in ShareMenu

---

src/components/priceRangeLabel/index.jsx
src/index.js
src/utils/mixins.js
stories/index.jsx

Create PriceRangeLabel component

---

src/components/listButton/index.jsx
stories/index.jsx

ListButton had some content specific to bookmarking which has been
removed and placed in the Bookmark component.
#381

Simplify ListButton component

---

src/components/bookmarkListAuthor/index.jsx
src/index.js
stories/index.jsx

Rename UserListAuthor to BookmarkListAuthor

---

package-lock.json
src/components/modalContent/modalContentMagicLinkForm.jsx
src/components/multiStep/multiStepLogin.jsx
stories/index.jsx

update legal copy
move copy above button for magic link form
fixes https://github.com/lonelyplanet/dotcom-profile/issues/143

update: move magicLinkForm disclaimer above confirm button

---

src/components/bookmarkListMenu/index.jsx
src/components/bookmarkListMenu/option.jsx
stories/index.jsx

Create BookmarkListMenu component

---

src/components/avatarUpload/index.jsx

need to listen to prop change so that new images will be set after mount

fix: update avatar image when prop changes

---

src/components/listItemBookmark/index.jsx
stories/index.jsx

The list item needs to be an anchor (to link to the list items in profile) or a button (when adding an item to a list).

Update bookmark list item

---

src/components/listItemBookmark/index.jsx

react-router’s Link component can be used to wrap each list item and
link to the list detail page

Remove href prop, change anchor to div in ListItemBookmark

---

src/components/albumThumbnailImage/index.jsx
stories/index.jsx

Size responds to font-size
* Add constants for size, overlayWidth
* Convert width, height and margins to em

Make AlbumThumbnailImage responsive

---

src/components/form/heightExpander.jsx
stories/index.jsx

text was being hidden if value was being passed in via props

fix: update height of SettingBlockText area on prop change

---

package-lock.json
src/components/settingBlock/settingBlockSection.jsx
src/components/settingBlock/settingBlockWrapper.jsx
src/components/settingBlockCheckbox/index.jsx

adds passthrough style prop
adds prop to control nested border on settingBlockWrapper

fix: pass style override through

---

src/components/listButton/index.jsx

* Remove box-shadow from focus styles
* Use margin to center icon horizontally in iOS

Update ListButton styles

---

src/components/bookmarkButton/index.jsx

Fix syntax errors introduced in previous pull request

---

src/components/listItemBookmark/index.jsx

Hover styles are placed on the containing anchor which is applied
at the app level.

Remove hover styles from ListItemBookmark

---

src/components/avatarUpload/index.jsx

photos uploaded with exif data currently are retaining gps data which could be  huge privacy concern. 
this removes the exif data and converts png's to jpgs by writing the image data to a canvas and then reading it back out as a dataUri to pass to the uploader

fix: remove exif data from avatar uploader

---

src/components/avatarUpload/index.jsx

need to convert datauri to blob

fix: convert url to image blob

---

src/components/bookmarkButton/index.jsx

Removed in favor of adding BookmarkButtonAlt

Remove iconType, responsive styles from BookmarkButton

---

src/components/bookmarkButtonAlt/index.jsx
stories/index.jsx

Styling is different enough from BookmarkButton that it can be its own component.

Create alternate bookmark button

---

src/components/listItemBookmark/index.jsx

Allows the component to be used as a "Create new list" button

Update list item bookmark component

---

src/components/settingBlock/settingBlock.jsx
src/components/settingBlock/settingBlockButtonDescription.jsx
src/components/settingBlock/settingBlockButtonWrapper.jsx
src/components/settingBlock/settingBlockDescription.jsx
src/components/settingBlock/settingBlockHeader.jsx
src/components/settingBlock/settingBlockListItemWrapper.jsx
src/components/settingBlock/settingBlockSection.jsx
src/components/settingBlock/settingBlockWrapper.jsx
src/components/settingBlockAccordion/index.jsx
src/components/settingBlockAction/index.jsx
src/components/settingBlockCheckbox/index.jsx
src/components/settingBlockInput/index.jsx
src/components/settingBlockTextArea/index.jsx
stories/index.jsx

* Clean up
* Allow type=radio for checkbox
* Replace heading with label win header
* Pass htmlFor props for the label when used with text inputs

Update setting block components

---

package-lock.json
package.json
src/components/shareMenu/clipboardWrapper.jsx
src/components/shareMenu/shareSettings.jsx
yarn.lock

create share wrapper to easily create facebook, twitter, email and copy link actions

feat: add shareSettings wrapper component

---

src/components/checkbox/checkboxComponent.jsx
src/components/icon/index.jsx

Old: <img src="https://user-images.githubusercontent.com/1479563/29969310-1d3ef0b0-8ee5-11e7-914d-ae588226ef27.png" width="48">
New: <img src="https://user-images.githubusercontent.com/1479563/29969285-0543014a-8ee5-11e7-9fe3-45fd1b302883.png" width="50">

Update checkbox styles, icon

---

src/components/modal/wrapper.jsx

```jsx
<ModalWrapper>
{(isOpen, toggle) => (
<Modal open={isOpen} onClose={toggle}>
…
</Modal>
)}
</ModalWrapper>
```

Add ModalWrapper component

---

src/components/listItemBookmark/index.jsx

Reduces duplication, gets the new checkbox styles

Use checkbox component for ListItemBookmark

---

src/components/listItemBookmark/index.jsx

https://github.com/lonelyplanet/dotcom-profile/issues/266

Remove blue from heading when ListItemBookmark is checked

---

src/components/listItemBookmark/index.jsx

Fixes bug where checkbox is too low

Update checkbox styles for ListItemBookmark

---

package-lock.json
src/components/listItemBookmark/index.jsx

add option to hide entire detail
add option to not show only visibility  (for public profile)

fix: add option to not show visibility status

---

src/components/switch/index.jsx
src/components/switch/switch.jsx
stories/index.jsx

Create switch component

---

src/components/iconButton/index.jsx
stories/index.jsx

Intended to replace ListButton component which is similar. Props and styles have been added to accommodate ListButton.

Refactor icon button component

---

src/components/input/index.jsx
src/components/textarea/index.jsx

* Add `innerRef` prop to Input
* Add `autofocus` prop to Textarea

Update input and textarea components

---

src/components/toast/index.jsx
stories/index.jsx

Update toast style

---

src/components/listItemBookmark/index.jsx

Allow name 2 lines, use line clamp in ListItemBookmark

---

src/components/listItemBookmark/index.jsx

Reference: https://github.com/lonelyplanet/dotcom-profile/issues/294

fix: add heart icon when list is named Favorites

---

src/components/listItemBookmarkEntry/index.jsx
stories/index.jsx

Allows for desktop sizing to be disabled on desktop (i.e. when in modal)

Add large prop to ListItemBookmarkEntry

---

src/components/flyout/index.jsx
src/components/listItemBookmarkEntry/index.jsx

adds edit and add note actions to bookmarkList entry 
fixed flyout arrow color

update: add note ui

---

src/components/listItemBookmarkEntry/index.jsx
src/components/textarea/index.jsx

when adding a value to textarea via props, the height was not auto adjusting. 
I call the functionality to autogrow on mount

fix: textarea grow on mount

---

package-lock.json
src/components/modalContent/modalContentLegacyLoginForm.jsx
src/components/modalContent/modalContentMagicLinkForm.jsx
src/components/multiStep/multiStepLogin.jsx

fix: update copy for auth modal

---

src/components/bookmarkListMenu/index.jsx

fixes https://github.com/lonelyplanet/backpack-ui/issues/496

fix: only close bookrmarkListMenu with esc

---

src/components/bookmarkListMenu/index.jsx

https://github.com/lonelyplanet/dotcom-profile/issues/331

Increase IconButton size in BookmarkListMenu

---

package-lock.json
package.json
yarn.lock

Seemed to be getting an error related to react-date-range in dotcom-pois. Updating seems to have resolved the error.

Update react-date-range to 0.9.4

---

src/components/flyout/index.jsx

error is no style object exists

fix: handle issue where style is not being passed to flyout

---

package-lock.json
package.json
src/components/bookmarkListMenu/index.jsx
stories/index.jsx

For: https://github.com/lonelyplanet/dotcom-profile/issues/312

feat: add reveal with flyout to bookmarkListMenu

---

package-lock.json
package.json
src/components/avatar/index.jsx
src/components/locationLabel/index.jsx
src/components/profileHeader/index.jsx
stories/index.jsx
yarn.lock

* Change layout
* Update styles
* Add website URL
* Add read more expander for intro/bio
* Add markdown renderer for legacy bios

Update ProfileHeader component

---

src/components/profileHeader/index.jsx

Provides better cross-browser support
https://codepen.io/siiron/details/jfBhy/

Improve line clamping for ProfileHeader bio

---

src/components/navigation/navigationTab.jsx

uses the dotted line border like we use on other components

fix: update navigation tab :focus styles

---

src/components/multiStep/multiStepLogin.jsx

update link and styles for disclaimer text on auth modal

fix: update disclaimer styles and text

---

src/components/modal/wrapper.jsx

https://github.com/lonelyplanet/dotcom-profile/issues/408
Commit message below explain what's going on and why.

Fix bug in iOS browsers where screen appears blank when modal opens

---

src/components/toast/index.jsx

* Change role from alert to alertdialog
* Define label and description as alertdialog
* Allow content to receive focus and describe it as a document

Make some accessibility improvements to Toast component

---

src/components/button/index.jsx
src/components/flightSearchWidget/index.jsx
src/utils/currencySymbols.js
src/utils/propTypes.js
src/utils/validations.js
stories/index.jsx

Uses react-measure to adjust styles based on component's width, aka element queries.

Create flight search widget

---

src/components/profileHeader/index.jsx

request: https://github.com/lonelyplanet/dotcom-profile/issues/436

fix: swap the name and location

---

src/components/modal/index.jsx

fixes https://github.com/lonelyplanet/dotcom-profile/issues/407

fix: cursor jumps out of inputs in modal

---

package-lock.json
src/components/pageHeader/index.jsx

increases heading size at mobile breakpoint
this was a design request for narratives in pois but I assume we should be making this change globally

fix: make pageHeader base header larger on mobile breakpoint

---

src/components/avatarUpload/index.jsx

request: https://github.com/lonelyplanet/backpack-ui/issues/518

fix: fix avatar uploader (use exif orientation)

---

src/components/profileHeader/index.jsx
src/utils/validations.js

Fixes: https://github.com/lonelyplanet/dotcom-profile/issues/448
Added capturing groups to urlRegex to create parser (dropped parsing via anchor element to keep same output server & client side).

Fix website link display

---

src/components/modal/index.jsx

I need this for https://github.com/lonelyplanet/dotcom-profile/pull/449

fix: allow hiding modal header

---

src/components/modal/index.jsx

request: https://github.com/lonelyplanet/backpack-ui/pull/564#issuecomment-347890858

fix: use default hideHeader instead of showHeader

---

.gitignore
src/components/checkbox/checkboxComponent.jsx
src/components/checkbox/index.jsx
src/components/form/input.jsx
src/components/newsletter/index.jsx
src/utils/keyCode.js
stories/index.jsx

* Send JSON data, use XHR
* Update UI and improve accessibility
https://github.com/lonelyplanet/wp-travelnews-frontend/issues/344

Update newsletter component

---

src/components/multiStep/multiStepLogin.jsx

request: https://github.com/lonelyplanet/dotcom-profile/issues/437
related: https://github.com/lonelyplanet/luna/pull/834

fix: add legacy login disclaimer

---

src/components/modalContent/modalContentMagicLinkForm.jsx

request: https://github.com/lonelyplanet/backpack-ui/issues/572

fix: don't use valid and showErrors state

---

src/components/auth/authContainer.jsx
src/components/auth/authDisclaimer.jsx
src/components/auth/authSocialButtons.jsx
src/components/disclaimerText/index.jsx
src/components/multiStep/multiStepLogin.jsx
src/components/toast/index.jsx

request: https://github.com/lonelyplanet/dotcom-profile/issues/255

fix: add gtm prefixes to class names

---

src/components/shareMenu/shareSettings.jsx
src/components/socialIconButton/index.jsx
src/styles/colors.js
stories/index.jsx

This update takes some features from SocialShareContainer, specifically:
* adding Facebook Messenger and Reddit URLs
* adding conditional to use `window.open` method only for share URLs that need it; for example, `mailto` links should not open a window.

Update ShareSettings component

---

src/components/newsletter/index.jsx
stories/index.jsx

update: allow newsletter form to auto optin with new legal requirements

---

package-lock.json
src/components/modal/wrapper.jsx

fix: check if hash prop exists before toggle

---

src/components/iconButton/index.jsx

Update IconButton component

---

src/components/cardVideo/index.jsx

Update CardVideo component

---

src/components/card/card.jsx
src/components/card/cardAnchor.jsx
src/components/card/cardHeading.jsx

Update card components

---

src/components/thumbnailListItem/index.jsx

* Add subtitle prop
* Add imageIcon prop
* Add imageIconLabel prop
* Add lineClamp prop
* Add style prop
* Add theme specific styles
#584

Update ThumbnailListItem component

---

src/components/cardShelfVideoSlider/index.jsx
src/components/thumbnailList/index.jsx
src/components/video/index.jsx
src/components/video/videoEmbed.jsx
src/components/video/videoFeatured.jsx
src/components/video/videoInfo.jsx
src/components/video/videoPlaylist.jsx
src/components/video/videoPlaylistWithSlider.jsx
src/components/video/videoPopout.jsx
src/components/video/videoSlider.jsx
src/components/video/videoUpNext.jsx

Takes #584 and places each new component into its own commit

Create new video components

---

src/components/spotlightZone/index.jsx

* Remove category prop
* Remove href prop
* Remove imageUrl prop
* Remove background overlay
* Add videoEmbed prop
* Add style prop
* Add VideoEmbed, VideoPopout components
* Update styles
#584 
Needs #594

Update SpotlightZone component

---

src/components/videoEmbed/index.jsx

#584 
This particular version of this component has been deprecated in favor of video/videoEmbed (see #594).

Update VideoEmbed component

---

src/components/toast/index.jsx

fix: toast with onClick action storyboard

---

stories/index.jsx

Group components by type to help take inventory of what’s here and what shouldn’t be here.

Clean up and organize stories by type

---

src/components/button/index.jsx
src/components/settingBlock/settingBlockButtonDescription.jsx
stories/index.jsx

fix: add new color option for button

---

src/components/tag/index.jsx
src/styles/colors.js

Update tag styles

---

src/styles/mq.js

These values correspond to the new template system using CSS grid
layout. The named values should make it easier to define breakpoints
for templates and layouts.

Add media query values for layout

---

src/components/video/videoEmbed.jsx
src/components/video/videoPlaylist.jsx
src/components/video/videoPlaylistWithSlider.jsx
src/components/video/videoSlider.jsx
stories/index.jsx

- Fixed issue with Video Info not appearing in `VideoPlaylistWithSlider`
- Fixed issue with slider pagination arrows not appearing when the slider initially comes into view in `VideoPlaylistWithSlider`
- Added 'JNTO' player name to `VideoEmbed` for upcoming Japan Destination page player.

feat: Added hideList prop to VideoPlaylist and VideoPlaylistWithSlider

---

src/components/bookmarkButton/index.jsx
stories/index.jsx

allow bookmarkbutton to handle passing a child button and icon component in with styles and props

feat: add child icon to bookmark button

---

src/components/video/videoPlaylist.jsx
src/components/video/videoPlaylistWithSlider.jsx

The interaction between `VideoPlaylist` and `VideoPlaylistWithSlider` continues to be non-intuitive to code around -- this will be cleaned up a bit in a week or so as we introduce a new player UI.   For now, these changes should be fine.

feat: Updated video playlist components to reshow featured video cover after playlist completes

---

package-lock.json
package.json
src/components/form/daterange.jsx
stories/index.jsx

this pulls in the updated version of the daterange picker that was built into dotcom-pois

fix: Update date range component and dependencies

---

src/components/form/select.jsx
stories/index.jsx

Requirement for partner pages form UI.
Objects require `label` and `value` keys.

Allow select component to accept array of objects

---

src/components/auth/authSocialButtons.jsx
src/components/multiStep/multiStepLogin.jsx

Added ability to disable certain authentication options in the UI. That feature will be used on the static authentication page, that's usually used only by 3rd party clients.

feat: add ability to disable given authentication options

---

src/components/video/videoEmbed.jsx
src/components/video/videoPlaylist.jsx

Also added a "copilot" player for copilot to use (has ads turned off, uses basic video ui, etc.)

feat: VideoPlaylist will show related videos in-player if hideList=true

---

src/components/form/select.jsx

Putting the `style` prop last in the array of styles will allow any passed in style to override the default styles.

Allow style prop to override default styles

---

package-lock.json
package.json
src/components/form/daterange.jsx
stories/index.jsx

* Adds the lastSelectableDate to the calendar to grey out selections past a certain date
* Opens the calendar on the selected date

feat: add lastSelectableDate to calendar

---

src/components/typeahead/typeahead.jsx

[DOT-600](https://lonelyplanet.atlassian.net/browse/DOT-600) This code will:
- Alter the meaning of the `<Typeahead>` component's `forceSelection` prop.
To this point, when active, it had been checking for the following:
- Has the user already made a selection?
- Has the user entered text that exactly matches one of the (filtered) options?
And if neither one of those conditions were true (ie, the user had entered incomplete text and no selection has been made yet), it would cause the selection to revert to the provided `initialValue` prop.
In practice, this typically appears to be `null`.
Note that if one of the options _had_ been entered (exactly, case-sensitively), then the user's input _wasn't_ being reset to `initialValue`, but the option that they entered was never actually being …

[DOT-600] Select First Search Result if forceSelection Prop Enabled

---

package-lock.json
package.json
spec/components/form/daterange.spec.js
spec/index.js
spec/utils/color.spec.js
spec/utils/grid.spec.js
spec/utils/mixins.spec.js
spec/utils/typography.spec.js
src/components/form/daterange.jsx
stories/index.jsx

This began as a bug fix but I think I determined that it was in
actuality an issue with the DateRangePicker dependency and not our
code, after implementing tests for our code. Adding tests allowed me to
refactor in a way that seems a bit more straightforward. Also fixed an
issue with the component that was firing React error messages in the
console.
Introduced enzyme as a library to help test React components, and
refactored existing tests a bit for improved visualization.

refactor: DateRange component outside range test

---

package-lock.json
package.json
src/utils/color.js

test coverage on this was good so that made this very easy

chore: update color dependency

---

CHANGELOG.md
package-lock.json
package.json

I'm probably just not doing something right, but `npm run push` (still) won't push to master for me.
Just gonna get it there this way instead.

chore(release): 4.90.5

---

src/components/newsletter/index.jsx
src/components/tabbedNav/index.jsx

These are bugs found from doing Merch QA [Issue TMB-47](https://lonelyplanet.atlassian.net/browse/TMB-47)
Issues:
- Email signup button text is truncated
- Tabbed nav when sticky is still showing transparently in IE
Resolutions:
- Add min width to the button so when default "sign up" is used, it will not be truncated
- Add background color to tabbed nav bar so it is not transparent

Kp qa fixes

---

src/components/newsletter/index.jsx

Issue found from doing Merch QA in this ticket [TMB-47](https://lonelyplanet.atlassian.net/browse/TMB-47)
Removed unnecessary styling in the Newsletter component which was causing issues in IE 11.

fix: remove unnecessary styling causing issues in IE 11

---

src/components/paginatorButton/index.jsx

This will allow the component to be used with CSS modules.

Add className prop to PaginatorButton component

---

src/components/sectionalNav/index.jsx

- added a few styles to reflect IE 11 transparency issues

fix: IE 11 style updates

---

src/components/navigation/navigation.jsx
src/components/sectionalNav/index.jsx
stories/index.jsx

- remove webkit style from navigation
- update sectional nav sticky functionality

Kp sectionalnav

---

src/components/video/videoPlaylistWithSlider.jsx

lineclamp is being passed false but is expecting a number
https://github.com/lonelyplanet/backpack-ui/blob/8dc8c7e430f3f68e55edc7e3f18c7602547c60fc/src/components/thumbnailListItem/index.jsx#L309

fix: lineclamp is expecting a number but is given a bool

---

package-lock.json
src/components/cardShelfVideoSlider/index.jsx
src/components/sponsorLabel/index.jsx
stories/index.jsx

It's the orange text at the top of this screenshot:

feat: added sponsorLabel prop to CardShelfVideoSlider component

---

package-lock.json
stories/index.jsx

I cannot figure out WHY (maybe that is a problem), but simply adding more and/or different data in the `slides` object fixes tallCarousel not rendering in storybook when component rendering screen width is above 839px... -_-

fix: change tallCarousel data

---

src/components/checkbox/checkboxComponent.jsx
src/components/newsletter/index.jsx

- update props validation to remove console warnings on newsletter component
- update newsletter text for higher SEO score per Will

fix: update props, update newsletter text

---

src/components/cardBook/index.jsx

fixes react warnings for cardBook component for the kids site.
- conditionally render optional props so that they don't have required warnings.

fix: conditionally render optional props in cardBook

---

package-lock.json
package.json
src/components/link/index.jsx

The `tallCarousel` stopped rendering because `slideTall Link` wasn't receiving a className anymore. This is critical for it to be styled in order to render properly. Added the className prop to the Link component so it now renders properly. I also bumped `react-slick`.

fix: update react-slick, update link

---

src/components/thumbnailListItem/index.jsx
src/components/video/videoPlaylist.jsx

squashin' bugs and takin' names

fix: change qahook propType to string to fix mismatch error

---

src/components/disclaimerText/index.jsx

Requested by John Falkum: [slack](https://lonelyplanet.slack.com/archives/C026V0UT3/p15717840980020000).

feat: Increase legacy login disclaimer fontsize

---

src/components/settingBlock/settingBlockButtonWrapper.jsx

issue with delete button reported by Hannah Horn here: https://lonelyplanet.slack.com/archives/C026V0UT3/p1585582488013000

fix: pass onClick handler
